language: cpp

matrix:
   include:

      - os: linux
   compiler: gcc-4.8
   script:
      - cmake . -DUSE_SUPERBUILD=ON -DBUILD_TESTS=ON
      - make 
      - cd test && ctest

      - os: osx
   compiler: clang
   script:
      - cmake . -DUSE_SUPERBUILD=ON -DBUILD_TESTS=ON
      - make 
      - cd test && ctest

