language: cpp

dist: xerus
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5.4


matrix:
   include:

      - os: linux
   compiler: gcc-5.4

      - os: osx
   compiler: clang



script:
   - cmake . -DUSE_SUPERBUILD=ON -DBUILD_TESTS=ON
   - make 
   - cd test && ctest

